/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package xamtastic.poleador;

import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Xavi
 */
public class Vista extends javax.swing.JFrame {

    /**
     * Creates new form Vista
     */
    public Vista() {

        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Bar1 = new javax.swing.JProgressBar();
        Label1 = new javax.swing.JLabel();
        Bar2 = new javax.swing.JProgressBar();
        Label2 = new javax.swing.JLabel();
        Bar5 = new javax.swing.JProgressBar();
        Bar3 = new javax.swing.JProgressBar();
        Label4 = new javax.swing.JLabel();
        Label3 = new javax.swing.JLabel();
        Label5 = new javax.swing.JLabel();
        Bar4 = new javax.swing.JProgressBar();
        Label10 = new javax.swing.JLabel();
        Label9 = new javax.swing.JLabel();
        Bar9 = new javax.swing.JProgressBar();
        Bar8 = new javax.swing.JProgressBar();
        Label8 = new javax.swing.JLabel();
        Bar7 = new javax.swing.JProgressBar();
        Label7 = new javax.swing.JLabel();
        Label6 = new javax.swing.JLabel();
        Bar6 = new javax.swing.JProgressBar();
        Bar10 = new javax.swing.JProgressBar();
        _titulo = new javax.swing.JLabel();
        TDSPTS = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        Bar1.setMaximumSize(new java.awt.Dimension(32767, 60));
        Bar1.setMinimumSize(new java.awt.Dimension(10, 60));
        Bar1.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                Bar1PropertyChange(evt);
            }
        });

        Label1.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        Label1.setText("Detectando nuevo hilo");
        Label1.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        Label1.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentHidden(java.awt.event.ComponentEvent evt) {
                Label1ComponentHidden(evt);
            }
            public void componentShown(java.awt.event.ComponentEvent evt) {
                Label1ComponentShown(evt);
            }
        });
        Label1.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                Label1PropertyChange(evt);
            }
        });

        Bar2.setMaximumSize(new java.awt.Dimension(32767, 60));
        Bar2.setMinimumSize(new java.awt.Dimension(10, 60));

        Label2.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        Label2.setText("Detectando OP parguela");

        Bar5.setMaximumSize(new java.awt.Dimension(32767, 60));
        Bar5.setMinimumSize(new java.awt.Dimension(10, 60));

        Bar3.setMaximumSize(new java.awt.Dimension(32767, 60));
        Bar3.setMinimumSize(new java.awt.Dimension(10, 60));

        Label4.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        Label4.setText("Escaneando contenido +18");

        Label3.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        Label3.setText("Detectando hilo presentacion sin prv");

        Label5.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        Label5.setText("Calibrando cantidad de pollas del hilo");

        Bar4.setMaximumSize(new java.awt.Dimension(32767, 60));
        Bar4.setMinimumSize(new java.awt.Dimension(10, 60));

        Label10.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        Label10.setText("Paja a la crema");

        Label9.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        Label9.setText("Tomando segundo vaso de agua");

        Bar9.setMaximumSize(new java.awt.Dimension(32767, 60));
        Bar9.setMinimumSize(new java.awt.Dimension(10, 60));

        Bar8.setMaximumSize(new java.awt.Dimension(32767, 60));
        Bar8.setMinimumSize(new java.awt.Dimension(10, 60));

        Label8.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        Label8.setText("Tomando vaso de agua");

        Bar7.setMaximumSize(new java.awt.Dimension(32767, 60));
        Bar7.setMinimumSize(new java.awt.Dimension(10, 60));

        Label7.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        Label7.setText("Flanderizando hilo");

        Label6.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        Label6.setText("Cargando reportadora");

        Bar6.setMaximumSize(new java.awt.Dimension(32767, 60));
        Bar6.setMinimumSize(new java.awt.Dimension(10, 60));

        Bar10.setMaximumSize(new java.awt.Dimension(32767, 60));
        Bar10.setMinimumSize(new java.awt.Dimension(10, 60));

        _titulo.setFont(new java.awt.Font("Dialog", 1, 58)); // NOI18N
        _titulo.setText("POLEADOR MAX POWER 2000");

        TDSPTS.setFont(new java.awt.Font("Dialog", 1, 120)); // NOI18N
        TDSPTS.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        TDSPTS.setText("TDS PTS");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Label1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Label3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Label7, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Label4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Label2, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Label8, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Label9, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Label6, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Label10, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Label5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Bar1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 468, Short.MAX_VALUE)
                    .addComponent(Bar2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Bar3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Bar4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Bar5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Bar6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Bar7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Bar8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Bar9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Bar10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(186, 186, 186)
                .addComponent(TDSPTS)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(46, Short.MAX_VALUE)
                .addComponent(_titulo)
                .addGap(35, 35, 35))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {Label1, Label10, Label2, Label3, Label4, Label5, Label6, Label7, Label8, Label9});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(_titulo, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Bar1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(8, 8, 8))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(Label1)
                        .addGap(18, 18, 18)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Label2)
                    .addComponent(Bar2, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Label3)
                    .addComponent(Bar3, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Label4, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Bar4, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Label5, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Bar5, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Label6)
                    .addComponent(Bar6, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Label7)
                    .addComponent(Bar7, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Label8)
                    .addComponent(Bar8, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Label9, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Bar9, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Label10, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Bar10, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addComponent(TDSPTS, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {Label1, Label10, Label2, Label3, Label4, Label5, Label6, Label7, Label8, Label9});

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {Bar1, Bar10, Bar2, Bar3, Bar4, Bar5, Bar6, Bar7, Bar8, Bar9});

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Bar1PropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_Bar1PropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_Bar1PropertyChange

    private void Label1PropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_Label1PropertyChange
        // TODO add your handling code here:
        setVisible(false);
    }//GEN-LAST:event_Label1PropertyChange

    private void Label1ComponentHidden(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_Label1ComponentHidden
        // TODO add your handling code here:
    }//GEN-LAST:event_Label1ComponentHidden

    private void Label1ComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_Label1ComponentShown
        // TODO add your handling code here:
    }//GEN-LAST:event_Label1ComponentShown

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */

        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Vista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Vista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Vista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Vista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new Vista().setVisible(true);
                Label1.setVisible(false);
                Label2.setVisible(false);
                Label4.setVisible(false);
                Label3.setVisible(false);
                Label5.setVisible(false);
                Label10.setVisible(false);
                Label9.setVisible(false);
                Label8.setVisible(false);
                Label7.setVisible(false);
                Label6.setVisible(false);
                TDSPTS.setVisible(false);
                Bar1.setVisible(false);
                Bar2.setVisible(false);
                Bar5.setVisible(false);
                Bar3.setVisible(false);
                Bar4.setVisible(false);
                Bar9.setVisible(false);
                Bar8.setVisible(false);
                Bar7.setVisible(false);
                Bar6.setVisible(false);
                Bar10.setVisible(false);
                _titulo.setVisible(true);

            }

        });
        int i = 0;
        try {
            java.util.concurrent.TimeUnit.MILLISECONDS.sleep(1000);
            Label1.setVisible(true);
            java.util.concurrent.TimeUnit.MILLISECONDS.sleep(300);
            Bar1.setVisible(true);
            while (i <= 100) {
                Bar1.setValue(i);
                i += 1;
                java.util.concurrent.TimeUnit.MILLISECONDS.sleep(17);
            }i=0;
            java.util.concurrent.TimeUnit.MILLISECONDS.sleep(1000);
            Label2.setVisible(true);
            java.util.concurrent.TimeUnit.MILLISECONDS.sleep(300);
            Bar2.setVisible(true);
            while (i <= 100) {
                Bar2.setValue(i);
                i += 1;
                java.util.concurrent.TimeUnit.MILLISECONDS.sleep(17);
            }i=0;
            java.util.concurrent.TimeUnit.MILLISECONDS.sleep(1000);
            Label3.setVisible(true);
            java.util.concurrent.TimeUnit.MILLISECONDS.sleep(300);
            Bar3.setVisible(true);
            while (i <= 100) {
                Bar3.setValue(i);
                i += 1;
                java.util.concurrent.TimeUnit.MILLISECONDS.sleep(17);
            }i=0;
            java.util.concurrent.TimeUnit.MILLISECONDS.sleep(1000);
            Label4.setVisible(true);
            java.util.concurrent.TimeUnit.MILLISECONDS.sleep(300);
            Bar4.setVisible(true);
while (i <= 100) {
                Bar4.setValue(i);
                i += 1;
                java.util.concurrent.TimeUnit.MILLISECONDS.sleep(17);
            }i=0;
            java.util.concurrent.TimeUnit.MILLISECONDS.sleep(1000);
            Label5.setVisible(true);
            java.util.concurrent.TimeUnit.MILLISECONDS.sleep(300);
            Bar5.setVisible(true);
while (i <= 100) {
                Bar5.setValue(i);
                i += 1;
                java.util.concurrent.TimeUnit.MILLISECONDS.sleep(17);
            }i=0;
            java.util.concurrent.TimeUnit.MILLISECONDS.sleep(1000);
            Label6.setVisible(true);
            java.util.concurrent.TimeUnit.MILLISECONDS.sleep(300);
            Bar6.setVisible(true);
while (i <= 100) {
                Bar6.setValue(i);
                i += 1;
                java.util.concurrent.TimeUnit.MILLISECONDS.sleep(17);
            }i=0;
            java.util.concurrent.TimeUnit.MILLISECONDS.sleep(1000);
            Label7.setVisible(true);
            java.util.concurrent.TimeUnit.MILLISECONDS.sleep(300);
            Bar7.setVisible(true);
while (i <= 100) {
                Bar7.setValue(i);
                i += 1;
                java.util.concurrent.TimeUnit.MILLISECONDS.sleep(17);
            }i=0;
            java.util.concurrent.TimeUnit.MILLISECONDS.sleep(1000);
            Label8.setVisible(true);
            java.util.concurrent.TimeUnit.MILLISECONDS.sleep(300);
            Bar8.setVisible(true);
while (i <= 100) {
                Bar8.setValue(i);
                i += 1;
                java.util.concurrent.TimeUnit.MILLISECONDS.sleep(17);
            }i=0;
            java.util.concurrent.TimeUnit.MILLISECONDS.sleep(1000);
            Label9.setVisible(true);
            java.util.concurrent.TimeUnit.MILLISECONDS.sleep(300);
            Bar9.setVisible(true);
while (i <= 100) {
                Bar9.setValue(i);
                i += 1;
                java.util.concurrent.TimeUnit.MILLISECONDS.sleep(17);
            }i=0;
            java.util.concurrent.TimeUnit.MILLISECONDS.sleep(1000);
            Label10.setVisible(true);
            java.util.concurrent.TimeUnit.MILLISECONDS.sleep(300);
            Bar10.setVisible(true);
while (i <= 100) {
                Bar10.setValue(i);
                i += 1;
                java.util.concurrent.TimeUnit.MILLISECONDS.sleep(17);
            }i=0;
            java.util.concurrent.TimeUnit.MILLISECONDS.sleep(1000);
            TDSPTS.setVisible(true);
            java.util.concurrent.TimeUnit.MILLISECONDS.sleep(600);
            TDSPTS.setVisible(false);
            java.util.concurrent.TimeUnit.MILLISECONDS.sleep(200);
            TDSPTS.setVisible(true);
            java.util.concurrent.TimeUnit.MILLISECONDS.sleep(600);
            TDSPTS.setVisible(false);
            java.util.concurrent.TimeUnit.MILLISECONDS.sleep(200);
            TDSPTS.setVisible(true);
            java.util.concurrent.TimeUnit.MILLISECONDS.sleep(600);
            TDSPTS.setVisible(false);
            java.util.concurrent.TimeUnit.MILLISECONDS.sleep(200);
            TDSPTS.setVisible(true);
            java.util.concurrent.TimeUnit.MILLISECONDS.sleep(600);
            TDSPTS.setVisible(false);
            java.util.concurrent.TimeUnit.MILLISECONDS.sleep(200);
            TDSPTS.setVisible(true);
            java.util.concurrent.TimeUnit.MILLISECONDS.sleep(600);
            TDSPTS.setVisible(false);
            java.util.concurrent.TimeUnit.MILLISECONDS.sleep(200);
            TDSPTS.setVisible(true);
            java.util.concurrent.TimeUnit.MILLISECONDS.sleep(600);
            TDSPTS.setVisible(false);
            java.util.concurrent.TimeUnit.MILLISECONDS.sleep(200);
            TDSPTS.setVisible(true);
            java.util.concurrent.TimeUnit.MILLISECONDS.sleep(600);
            TDSPTS.setVisible(false);
            java.util.concurrent.TimeUnit.MILLISECONDS.sleep(200);
            TDSPTS.setVisible(true);
            java.util.concurrent.TimeUnit.MILLISECONDS.sleep(600);
            TDSPTS.setVisible(false);
            java.util.concurrent.TimeUnit.MILLISECONDS.sleep(200);
            TDSPTS.setVisible(true);
            java.util.concurrent.TimeUnit.MILLISECONDS.sleep(600);
            TDSPTS.setVisible(false);
            java.util.concurrent.TimeUnit.MILLISECONDS.sleep(200);
            TDSPTS.setVisible(true);
            java.util.concurrent.TimeUnit.MILLISECONDS.sleep(600);
            TDSPTS.setVisible(false);
            java.util.concurrent.TimeUnit.MILLISECONDS.sleep(200);
            TDSPTS.setVisible(true);
            java.util.concurrent.TimeUnit.MILLISECONDS.sleep(600);
            TDSPTS.setVisible(false);
            java.util.concurrent.TimeUnit.MILLISECONDS.sleep(200);
            TDSPTS.setVisible(true);
            java.util.concurrent.TimeUnit.MILLISECONDS.sleep(600);
            TDSPTS.setVisible(false);
            java.util.concurrent.TimeUnit.MILLISECONDS.sleep(200);
            TDSPTS.setVisible(true);
        } catch (InterruptedException ex) {
            Logger.getLogger(Vista.class.getName()).log(Level.SEVERE, null, ex);
        }

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private static javax.swing.JProgressBar Bar1;
    private static javax.swing.JProgressBar Bar10;
    private static javax.swing.JProgressBar Bar2;
    private static javax.swing.JProgressBar Bar3;
    private static javax.swing.JProgressBar Bar4;
    private static javax.swing.JProgressBar Bar5;
    private static javax.swing.JProgressBar Bar6;
    private static javax.swing.JProgressBar Bar7;
    private static javax.swing.JProgressBar Bar8;
    private static javax.swing.JProgressBar Bar9;
    private static javax.swing.JLabel Label1;
    private static javax.swing.JLabel Label10;
    private static javax.swing.JLabel Label2;
    private static javax.swing.JLabel Label3;
    private static javax.swing.JLabel Label4;
    private static javax.swing.JLabel Label5;
    private static javax.swing.JLabel Label6;
    private static javax.swing.JLabel Label7;
    private static javax.swing.JLabel Label8;
    private static javax.swing.JLabel Label9;
    private static javax.swing.JLabel TDSPTS;
    private static javax.swing.JLabel _titulo;
    // End of variables declaration//GEN-END:variables
}
